# Generated by Django 6.0 on 2026-06-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='images/categories/roller-blinds.webp', help_text='Example: images/categories/roller-blinds.webp', max_length=255),
        ),
    ]
