# Generated by Django 6.0 on 2026-06-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., About Us, Fabrics Collection', max_length=50)),
                ('url_name', models.CharField(default='#', help_text="Django named URL pattern (e.g., 'home') or external/relative path (e.g., '#')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the left-to-right sorting position of the menu link')),
                ('is_premium_highlight', models.BooleanField(default=False, help_text='Check this to give it the glowing gold text effect (like D2V Marketing Club)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
