# Generated by Django 6.0 on 2026-06-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_navitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave blank if this is a main, top-level menu item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.navitem'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='is_premium_highlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls sorting order position'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='title',
            field=models.CharField(help_text='e.g., About Us, Fabrics', max_length=50),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='url_name',
            field=models.CharField(default='#', help_text='Named URL pattern or target route hash', max_length=100),
        ),
    ]
