# Generated by Django 6.0 on 2026-06-10 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_navitem_parent_alter_navitem_is_premium_highlight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='fabrics/default.webp', upload_to='fabrics/')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls sorting display order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='shop.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
