# Generated by Django 6.0 on 2026-06-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_fabrictype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
