# Generated by Django 6.0 on 2026-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_options_remove_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='highlight_1',
            field=models.CharField(default='Custom built sizing explicitly engineered around your window configurations.', help_text='First bullet point highlight', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='highlight_2',
            field=models.CharField(default='Premium luxury durability optimized for smooth everyday deployment tracking.', help_text='Second bullet point highlight', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='highlight_3',
            field=models.CharField(default='Advanced protection safeguards blocking harmful UV fading exposure.', help_text='Third bullet point highlight', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of this specific treatment.', null=True),
        ),
    ]
