# Generated by Django 6.0 on 2026-06-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_highlight_1_category_highlight_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck this to hide the category from the website.'),
        ),
    ]
