# Generated by Django 6.0 on 2026-06-11 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Solar Protection, Glare Control', max_length=100)),
                ('image', models.ImageField(default='fabrics/features/default.webp', upload_to='fabrics/features/')),
                ('description', models.TextField(help_text='Short detail explaining this design perk.')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.fabrictype')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUsReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Expert Craftsmanship, Perfect Fit', max_length=150)),
                ('details', models.TextField(help_text='Detailed value proposition explanation.')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='shop.fabrictype')),
            ],
        ),
    ]
