# Generated by Django 6.0 on 2026-06-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_fabricfeature_whychooseusreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload additional style or swatch images.', upload_to='fabrics/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Optional description for accessibility and SEO.', max_length=150)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls order of appearance.')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='shop.fabrictype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
